# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\x12\x05\x62ooks\"?\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\"\x19\n\x0b\x42ookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\x0c\x42ookResponse\x12\x19\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0b.books.Book\"\x12\n\x10ListBooksRequest\"/\n\x11ListBooksResponse\x12\x1a\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0b.books.Book\"=\n\x0e\x41\x64\x64\x42ookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\"6\n\x12\x44\x65leteBookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x81\x02\n\x0b\x42ookService\x12\x35\n\x08get_book\x12\x12.books.BookRequest\x1a\x13.books.BookResponse\"\x00\x12\x41\n\nlist_books\x12\x17.books.ListBooksRequest\x1a\x18.books.ListBooksResponse\"\x00\x12\x38\n\x08\x61\x64\x64_book\x12\x15.books.AddBookRequest\x1a\x13.books.BookResponse\"\x00\x12>\n\x0b\x64\x65lete_book\x12\x12.books.BookRequest\x1a\x19.books.DeleteBookResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOK']._serialized_start=22
  _globals['_BOOK']._serialized_end=85
  _globals['_BOOKREQUEST']._serialized_start=87
  _globals['_BOOKREQUEST']._serialized_end=112
  _globals['_BOOKRESPONSE']._serialized_start=114
  _globals['_BOOKRESPONSE']._serialized_end=155
  _globals['_LISTBOOKSREQUEST']._serialized_start=157
  _globals['_LISTBOOKSREQUEST']._serialized_end=175
  _globals['_LISTBOOKSRESPONSE']._serialized_start=177
  _globals['_LISTBOOKSRESPONSE']._serialized_end=224
  _globals['_ADDBOOKREQUEST']._serialized_start=226
  _globals['_ADDBOOKREQUEST']._serialized_end=287
  _globals['_DELETEBOOKRESPONSE']._serialized_start=289
  _globals['_DELETEBOOKRESPONSE']._serialized_end=343
  _globals['_BOOKSERVICE']._serialized_start=346
  _globals['_BOOKSERVICE']._serialized_end=603
# @@protoc_insertion_point(module_scope)
